set positional-arguments

# default recipe to display help information
default:
    @just --list

# Spawns the devnet
devnet-up: build
    kurtosis run . --args-file network_params.yaml --enclave world-chain

# Stops the devnet **This will prune all docker containers**
devnet-down:
    kurtosis enclave rm -f world-chain
    kurtosis clean

# Builds and tags the world-chain-builder
build: build-world-chain

build-world-chain:
    docker buildx build -t world-chain-builder:latest -f ../world-chain-builder/Dockerfile ../world-chain-builder

fixtures:
    chmod +x fixtures.sh && ./fixtures.sh
