set positional-arguments

# Tests the world-chain-builder
test:
    cargo test

# Formats the world-chain-builder
fmt: fmt-fix fmt-check

fmt-fix:
  cargo +nightly fmt --all

fmt-check:
  cargo +nightly fmt --all -- --check

# Runs the block building assertions
assertor *args='':
    cargo run --package assertor -- $@
