set positional-arguments

# Tests the world-chain-builder
test:
    cargo test -- --test-threads=1

# Formats the world-chain-builder
fmt:
    cargo fmt

# Runs the block building assertions
assertor *args='':
    cargo run --package assertor -- $@