set positional-arguments

# Tests the world-chain-builder
test:
    cargo test -- --test-threads=1

# Formats the world-chain-builder
fmt: fmt-fix fmt-check

fmt-fix:
  cargo +nightly fmt --all

fmt-check:
  cargo +nightly fmt --all -- --check

e2e-test:
    RUST_LOG=info cargo run -p tests --release 

